services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    environment:
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
      - TZ=Asia/Seoul
    volumes:
      - ./app/data:/chatbot/app/data
    restart: unless-stopped
    # Linux에서 host.docker.internal을 사용할 수 있도록 설정
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

    
    
    