name: Sync fork with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORK_PAT }}
          fetch-depth: 0
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/incheon-time-traveler/time-travel-ai-chatbot.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.FORK_PAT }}
          commit-messages: "Sync fork with upstream"
          title: "Sync fork with upstream"
          body: "자동 생성된 PR: upstream/master -> fork/master"
          branch: sync-upstream/master
          base: master